### ISSUE TITLE
USER STORY:  Users can provide anonymous feedback in the poll

### ISSUE THREAD

**Issue by NickdevC** [NickdevC/My-First-Agile-Project#5]
In order to **provide anonymous feedback** as a **user** I can **choose to hide my identity in the poll response*

### Acceptance Criteria:

- Each option should be a checkbox
- The options should appear next to the submit button
- After submitting, the default submission confirmation should be adjusted to include the user name

### Tasks

- [ ] Update the view: the poll design (HTML and CSS) to include checkbox and show name of submitter
- [ ] Create a new field in the model to track the username 
- [ ] Update the controller function
- [ ] Test functionality
